version: '3.8'

services:
  app:
    build: .
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped